sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t trinhno/learn-docker-react .

script:
  - docker run -e CI=true trinhno/learn-docker-react npm run test
